export const NAME: "auth" = "auth";

export const SET_USER_DATA: `SET_DATA` = `SET_DATA`;
export const SET_AUTH_CHECKING: `SET_AUTH_CHECKING` = `SET_AUTH_CHECKING`;

export const SET_REGISTER_SENDING: `SET_REGISTER_SENDING` = `SET_REGISTER_SENDING`;
export const SET_REGISTER_SEND_ERROR: `SET_REGISTER_SEND_ERROR` = `SET_REGISTER_SEND_ERROR`;

export const SET_LOGIN_SENDING: `SET_LOGIN_SENDING` = `SET_LOGIN_SENDING`;
export const SET_LOGIN_SEND_ERROR: `SET_LOGIN_SEND_ERROR` = `SET_LOGIN_SEND_ERROR`;

export const SET_PASSWORD_FORGOT_EMAIL_SEND: `SET_PASSWORD_FORGOT_EMAIL_SEND` = `SET_PASSWORD_FORGOT_EMAIL_SEND`;
export const SET_PASSWORD_FORGOT_CHANGED: `SET_PASSWORD_FORGOT_CHANGED` = `SET_PASSWORD_FORGOT_CHANGED`;
export const SET_RESET_PASSWORD_FORGOT_ERROR: `SET_RESET_PASSWORD_FORGOT_ERROR` = `SET_RESET_PASSWORD_FORGOT_ERROR`;
export const RESET_PASSWORD_FORGOT: `RESET_PASSWORD_FORGOT` = `RESET_PASSWORD_FORGOT`;
