export const NAME: "constructorBurger" = "constructorBurger";
export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT: "REMOVE_INGREDIENT" = "REMOVE_INGREDIENT";
export const RESET_CONSTRUCTOR: "RESET_CONSTRUCTOR" = "RESET_CONSTRUCTOR";
export const UPDATE_CONSTRUCTOR: "UPDATE_CONSTRUCTOR" = "UPDATE_CONSTRUCTOR";
