export const NAME: "currentUser" = "currentUser";

export const UPDATE_USER_DATA: "UPDATE_USER_DATA" = `UPDATE_USER_DATA`;
export const UPDATE_USER_DATA_SEND: "UPDATE_USER_DATA_SEND" = `UPDATE_USER_DATA_SEND`;
export const UPDATE_USER_DATA_ERROR: "UPDATE_USER_DATA_ERROR" = `UPDATE_USER_DATA_ERROR`;
